import { promises as fs } from "fs";
import path from "path";
import { parse, format } from "date-fns";
import {
    getTaxDeductibilityForExpense,
    normalizeDescriptionForExpense,
    getPaymentAccountForExpense,
    getPaymentDateForExpense,
    pickCompany,
} from "./rules.js";
import safe from "safe-await";
import * as p from "@clack/prompts";
import { extractInvoiceFromPdf, getActiveProvider } from "./llm/index.js";
import { fetchModelPricesById, toLlmPriceModelId } from "./llm/pricing.js";

import {
    listCompanies,
    createReceivedDocument,
    deleteReceivedDocument,
    uploadAttachment,
    getOrCreateSupplier,
    previewSupplierResolution,
    findCurrency,
    findPaymentAccount,
} from "./fatture-in-cloud.js";

const EXPENSE_DETAILS_URL = "https://secure.fattureincloud.it/expenses/view";
const RUN_LOG_FILE = process.env.RUN_LOG_FILE || "RUN_LOG.md";
const ROLLBACK_HISTORY_FILE = process.env.ROLLBACK_HISTORY_FILE || "rollback-history.json";

function truncateFilename(file) {
    return file.length > 30 ? file.substring(0, 30) : file;
}

function isExtraEuDescription(description) {
    return typeof description === "string" && description.toLowerCase().includes("extraeu");
}

function toDisplayValue(value) {
    if (value === null || value === undefined || value === "") {
        return "-";
    }
    if (typeof value === "number" && Number.isFinite(value)) {
        return Number(value.toFixed(8)).toString();
    }

    return String(value);
}

function escapeMarkdownCell(value) {
    return toDisplayValue(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function createMarkdownTable(columns, rows) {
    const header = `| ${columns.join(" | ")} |`;
    const separator = `| ${columns.map(() => "---").join(" | ")} |`;
    const body = rows.map((row) => `| ${columns.map((column) => escapeMarkdownCell(row[column])).join(" | ")} |`);

    return [header, separator, ...body].join("\n");
}

async function ensureRunLogFile(logFilePath) {
    const [accessError] = await safe(fs.access(logFilePath));
    if (!accessError) {
        return;
    }

    const directoryPath = path.dirname(logFilePath);
    const [mkdirError] = await safe(fs.mkdir(directoryPath, { recursive: true }));
    if (mkdirError && directoryPath !== ".") {
        throw mkdirError;
    }

    const [writeError] = await safe(
        fs.writeFile(
            logFilePath,
            "# Run Log\n\nThis file is auto-generated by the importer. Each run appends a new section.\n\n"
        )
    );
    if (writeError) {
        throw writeError;
    }
}

async function appendRunLog({ executionType, activeProvider, filesFound, recap, llmRecap, logFilePath }) {
    await ensureRunLogFile(logFilePath);

    const nowIso = new Date().toISOString();
    const lines = [
        `## Run ${nowIso}`,
        `- Mode: \`${executionType}\``,
        `- Provider: \`${activeProvider}\``,
        `- Files found: ${filesFound}`,
        `- Expenses processed: ${recap.length}`,
        "",
        "### Expenses",
    ];

    if (recap.length > 0) {
        lines.push(
            createMarkdownTable(
                [
                    "file",
                    "date",
                    "description",
                    "extraeu",
                    "amount_gross",
                    "tax_deductibility",
                    "entity_status",
                    "entity_name",
                    "entity_id",
                    "status",
                    "id",
                    "url",
                ],
                recap
            )
        );
    } else {
        lines.push("_No expense rows._");
    }

    lines.push("");
    lines.push("### LLM Totals");
    lines.push(
        createMarkdownTable(
            ["input_tokens", "output_tokens", "total_tokens", "input_cost_usd", "output_cost_usd", "total_cost_usd"],
            [llmRecap.totals]
        )
    );
    lines.push("");
    lines.push("### LLM Usage Per File");
    lines.push(
        createMarkdownTable(
            [
                "file",
                "provider",
                "model",
                "llm_price_model_id",
                "input_tokens",
                "output_tokens",
                "total_tokens",
                "total_cost_usd",
            ],
            llmRecap.rowsWithCosts
        )
    );

    if (llmRecap.totalsByProviderModel.length > 1) {
        lines.push("");
        lines.push("### LLM Totals By Provider/Model");
        lines.push(
            createMarkdownTable(
                [
                    "provider",
                    "model",
                    "llm_price_model_id",
                    "input_tokens",
                    "output_tokens",
                    "total_tokens",
                    "total_cost_usd",
                ],
                llmRecap.totalsByProviderModel
            )
        );
    }

    if (llmRecap.pricingFetchError) {
        lines.push("");
        lines.push(`- Pricing fetch warning: ${llmRecap.pricingFetchError}`);
    }

    if (llmRecap.missingModelIds.length > 0) {
        lines.push("");
        lines.push(`- Missing price model ids: ${llmRecap.missingModelIds.join(", ")}`);
    }

    lines.push("");
    lines.push("---");
    lines.push("");

    const [appendError] = await safe(fs.appendFile(logFilePath, lines.join("\n")));
    if (appendError) {
        throw appendError;
    }
}

function createEmptyLlmRecap() {
    return {
        pricingFetchError: null,
        missingModelIds: [],
        rowsWithCosts: [],
        totals: {
            input_tokens: 0,
            output_tokens: 0,
            total_tokens: 0,
            input_cost_usd: 0,
            output_cost_usd: 0,
            total_cost_usd: 0,
        },
        totalsByProviderModel: [],
    };
}

async function loadRollbackHistory(historyFilePath) {
    const [readError, content] = await safe(fs.readFile(historyFilePath, "utf-8"));
    if (readError) {
        if (readError.code === "ENOENT") {
            return [];
        }
        throw readError;
    }

    let parsed;
    try {
        parsed = JSON.parse(content);
    } catch (error) {
        throw new Error(`Invalid JSON in rollback history file: ${historyFilePath}`);
    }

    if (Array.isArray(parsed)) {
        return parsed;
    }
    if (parsed && Array.isArray(parsed.entries)) {
        return parsed.entries;
    }

    throw new Error(`Rollback history file must contain an array: ${historyFilePath}`);
}

async function saveRollbackHistory(historyFilePath, entries) {
    const directoryPath = path.dirname(historyFilePath);
    const [mkdirError] = await safe(fs.mkdir(directoryPath, { recursive: true }));
    if (mkdirError && directoryPath !== ".") {
        throw mkdirError;
    }

    const [writeError] = await safe(fs.writeFile(historyFilePath, `${JSON.stringify(entries, null, 2)}\n`, "utf-8"));
    if (writeError) {
        throw writeError;
    }
}

async function appendRollbackHistoryEntry(historyFilePath, entry) {
    const entries = await loadRollbackHistory(historyFilePath);
    entries.push(entry);
    await saveRollbackHistory(historyFilePath, entries);
}

function createRollbackHistoryEntryId() {
    return `rb_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`;
}

function createRollbackRecapRow(entry, status) {
    const expenseId = entry.received_document_id || "-";
    return {
        file: truncateFilename(entry.file_name || "-"),
        date: entry.date || "-",
        description: entry.description || "ROLLBACK",
        extraeu: isExtraEuDescription(entry.description),
        amount_gross: entry.amount_gross ?? "-",
        tax_deductibility: entry.tax_deductibility ?? "-",
        entity_status: entry.entity_status || "-",
        entity_name: entry.entity_name || "-",
        entity_id: entry.entity_id || "-",
        status,
        id: expenseId,
        url: expenseId === "-" ? "-" : `${EXPENSE_DETAILS_URL}/${expenseId}`,
    };
}

function rollbackOptionLabel(entry) {
    const amount = entry.amount_gross ?? "-";
    const description = entry.description || "-";
    return `${entry.file_name || "-"} | id:${entry.received_document_id || "-"} | ${description} | ${amount}`;
}

function toErrorText(error) {
    if (!error) {
        return "unknown_error";
    }
    return error.response?.data?.error || error.message || String(error);
}

async function runRollbackMode({ historyFilePath, runLogPath, activeProvider }) {
    const history = await loadRollbackHistory(historyFilePath);

    const rollbackCandidates = history
        .map((entry, historyIndex) => ({
            entry,
            historyIndex,
        }))
        .filter(({ entry }) => {
            const status = entry?.status || "created";
            const canRollbackStatus = status === "created" || status === "rollback_partial";
            return canRollbackStatus && entry?.company_id && entry?.received_document_id;
        });

    if (rollbackCandidates.length === 0) {
        p.log.info(`No rollback candidates found in ${historyFilePath}`);
        return;
    }

    p.log.info(`Rollback history: ${historyFilePath}`);

    const selectedHistoryIndexes = await p.multiselect({
        message: "Select one or more expenses to rollback",
        options: rollbackCandidates.map(({ entry, historyIndex }) => ({
            value: historyIndex,
            label: rollbackOptionLabel(entry),
        })),
        required: true,
    });

    if (p.isCancel(selectedHistoryIndexes)) {
        p.log.error("Operation cancelled.");
        process.exit(0);
    }

    if (!selectedHistoryIndexes || selectedHistoryIndexes.length === 0) {
        p.log.warn("No expenses selected for rollback.");
        return;
    }

    const confirmed = await p.confirm({
        message: `Confirm rollback of ${selectedHistoryIndexes.length} expense(s)?`,
        active: "Yes, rollback",
        inactive: "No",
    });

    if (p.isCancel(confirmed) || !confirmed) {
        p.log.error("Operation cancelled.");
        process.exit(0);
    }

    const rollbackRecap = [];
    let successCount = 0;
    let partialCount = 0;
    let deleteSuccessCount = 0;
    let restoreSuccessCount = 0;

    for (const historyIndex of selectedHistoryIndexes) {
        const entry = history[historyIndex];
        if (!entry) {
            continue;
        }

        const errors = [];
        let remoteDeleted = false;
        let fileRestored = false;

        const [deleteError] = await safe(deleteReceivedDocument(entry.company_id, entry.received_document_id));
        if (deleteError) {
            if (deleteError.response?.status === 404) {
                // Already deleted remotely in a previous attempt.
                remoteDeleted = true;
                deleteSuccessCount += 1;
            } else {
                errors.push(`delete: ${toErrorText(deleteError)}`);
            }
        } else {
            remoteDeleted = true;
            deleteSuccessCount += 1;
        }

        const sourcePath = entry.source_path ? path.resolve(entry.source_path) : null;
        const donePath = entry.done_path ? path.resolve(entry.done_path) : null;

        if (!sourcePath || !donePath) {
            errors.push("restore: missing source_path or done_path in history");
        } else {
            const [doneAccessError] = await safe(fs.access(donePath));
            if (doneAccessError) {
                errors.push(`restore: done file not accessible (${donePath})`);
            } else {
                const [sourceAccessError] = await safe(fs.access(sourcePath));
                if (!sourceAccessError) {
                    errors.push(`restore: source file already exists (${sourcePath})`);
                } else if (sourceAccessError.code !== "ENOENT") {
                    errors.push(`restore: source file not accessible (${sourcePath})`);
                } else {
                    const [mkdirError] = await safe(fs.mkdir(path.dirname(sourcePath), { recursive: true }));
                    if (mkdirError) {
                        errors.push(`restore: unable to create source dir (${toErrorText(mkdirError)})`);
                    } else {
                        const [restoreError] = await safe(fs.rename(donePath, sourcePath));
                        if (restoreError) {
                            errors.push(`restore: ${toErrorText(restoreError)}`);
                        } else {
                            fileRestored = true;
                            restoreSuccessCount += 1;
                        }
                    }
                }
            }
        }

        const nowIso = new Date().toISOString();
        const isSuccess = remoteDeleted && fileRestored;
        const newStatus = isSuccess ? "rolled_back" : "rollback_partial";
        const rollbackEvent = {
            at: nowIso,
            action: "rollback",
            remote_deleted: remoteDeleted,
            file_restored: fileRestored,
            errors,
        };
        const previousEvents = Array.isArray(entry.rollback_events) ? entry.rollback_events : [];

        history[historyIndex] = {
            ...entry,
            status: newStatus,
            updated_at: nowIso,
            rollback_events: [...previousEvents, rollbackEvent],
        };

        if (isSuccess) {
            successCount += 1;
            p.log.success(`Rolled back ${entry.file_name} [expense id: ${entry.received_document_id}]`);
        } else {
            partialCount += 1;
            p.log.warn(
                `Rollback partial for ${entry.file_name} [expense id: ${entry.received_document_id}] - ${errors.join(
                    "; "
                )}`
            );
        }

        rollbackRecap.push(createRollbackRecapRow(history[historyIndex], isSuccess ? "rolled-back" : "rollback-partial"));
    }

    await saveRollbackHistory(historyFilePath, history);

    console.table(rollbackRecap);
    p.log.info(
        `Rollback complete: success ${successCount}, partial ${partialCount}, remote deleted ${deleteSuccessCount}, files restored ${restoreSuccessCount}`
    );

    const [logError] = await safe(
        appendRunLog({
            executionType: "rollback",
            activeProvider,
            filesFound: selectedHistoryIndexes.length,
            recap: rollbackRecap,
            llmRecap: createEmptyLlmRecap(),
            logFilePath: runLogPath,
        })
    );

    if (logError) {
        p.log.warn(`Unable to append run log at ${runLogPath}: ${logError.message || String(logError)}`);
    } else {
        p.log.info(`Run log updated: ${runLogPath}`);
    }
}

function toRoundedNumber(value, decimals = 8) {
    if (!Number.isFinite(value)) {
        return null;
    }

    return Number(value.toFixed(decimals));
}

function computeCost(tokens, unitPrice) {
    if (!Number.isFinite(tokens) || !Number.isFinite(unitPrice)) {
        return null;
    }

    return tokens * unitPrice;
}

function createEmptyLlmTotals() {
    return {
        input_tokens: 0,
        output_tokens: 0,
        total_tokens: 0,
        input_cost_usd: 0,
        output_cost_usd: 0,
        total_cost_usd: 0,
    };
}

function mergeLlmTotals(target, source) {
    if (Number.isFinite(source.input_tokens)) {
        target.input_tokens += source.input_tokens;
    }
    if (Number.isFinite(source.output_tokens)) {
        target.output_tokens += source.output_tokens;
    }
    if (Number.isFinite(source.total_tokens)) {
        target.total_tokens += source.total_tokens;
    }
    if (Number.isFinite(source.input_cost_usd)) {
        target.input_cost_usd += source.input_cost_usd;
    }
    if (Number.isFinite(source.output_cost_usd)) {
        target.output_cost_usd += source.output_cost_usd;
    }
    if (Number.isFinite(source.total_cost_usd)) {
        target.total_cost_usd += source.total_cost_usd;
    }
}

async function buildLlmCostRecap(llmUsageRows) {
    const rowsWithPriceModel = llmUsageRows.map((row) => ({
        ...row,
        llm_price_model_id: toLlmPriceModelId({
            provider: row.provider,
            model: row.model,
        }),
    }));

    const uniquePriceModelIds = [...new Set(rowsWithPriceModel.map((row) => row.llm_price_model_id).filter(Boolean))];

    let pricesByModelId = {};
    let missingModelIds = [];
    let pricingFetchError = null;

    if (uniquePriceModelIds.length > 0) {
        const [pricingError, pricingResult] = await safe(fetchModelPricesById(uniquePriceModelIds));
        if (pricingError) {
            pricingFetchError = pricingError.message || String(pricingError);
        } else {
            pricesByModelId = pricingResult.pricesByModelId;
            missingModelIds = pricingResult.missingModelIds;
        }
    }

    const totals = createEmptyLlmTotals();
    const totalsByProviderModel = {};

    const rowsWithCosts = rowsWithPriceModel.map((row) => {
        const price = row.llm_price_model_id ? pricesByModelId[row.llm_price_model_id] : null;

        const inputCost = computeCost(row.input_tokens, price?.prompt);
        const outputCost = computeCost(row.output_tokens, price?.completion);
        const totalCost = Number.isFinite(inputCost) && Number.isFinite(outputCost) ? inputCost + outputCost : null;

        const normalizedRow = {
            ...row,
            input_cost_usd: inputCost,
            output_cost_usd: outputCost,
            total_cost_usd: totalCost,
        };

        mergeLlmTotals(totals, normalizedRow);

        const providerModelKey = `${row.provider || "unknown"}|${row.model || "unknown"}`;
        if (!totalsByProviderModel[providerModelKey]) {
            totalsByProviderModel[providerModelKey] = {
                provider: row.provider || "unknown",
                model: row.model || "unknown",
                llm_price_model_id: row.llm_price_model_id || null,
                ...createEmptyLlmTotals(),
            };
        }
        mergeLlmTotals(totalsByProviderModel[providerModelKey], normalizedRow);

        return {
            file: row.file,
            provider: row.provider || "unknown",
            model: row.model || "unknown",
            llm_price_model_id: row.llm_price_model_id || "n/a",
            input_tokens: row.input_tokens,
            output_tokens: row.output_tokens,
            total_tokens: row.total_tokens,
            input_cost_usd: toRoundedNumber(inputCost),
            output_cost_usd: toRoundedNumber(outputCost),
            total_cost_usd: toRoundedNumber(totalCost),
        };
    });

    return {
        pricingFetchError,
        missingModelIds,
        rowsWithCosts,
        totals: {
            input_tokens: totals.input_tokens,
            output_tokens: totals.output_tokens,
            total_tokens: totals.total_tokens,
            input_cost_usd: toRoundedNumber(totals.input_cost_usd),
            output_cost_usd: toRoundedNumber(totals.output_cost_usd),
            total_cost_usd: toRoundedNumber(totals.total_cost_usd),
        },
        totalsByProviderModel: Object.values(totalsByProviderModel).map((row) => ({
            ...row,
            input_cost_usd: toRoundedNumber(row.input_cost_usd),
            output_cost_usd: toRoundedNumber(row.output_cost_usd),
            total_cost_usd: toRoundedNumber(row.total_cost_usd),
        })),
    };
}

/**
 * Processes a PDF file with the configured LLM provider and normalizes invoice data
 * @param {Buffer} pdfBuffer - The PDF file buffer to process
 * @returns {Promise<Object>} The extracted and processed invoice data
 * @throws {Error} If processing fails
 */
async function processPDFWithLLM(pdfBuffer) {
    // Read the prompt from the file
    const [promptError, prompt] = await safe(fs.readFile("prompt.txt", "utf-8"));
    if (promptError) {
        console.error("Error reading prompt file:", promptError);
        throw promptError;
    }

    const [extractError, extractionResult] = await safe(
        extractInvoiceFromPdf({
            pdfBuffer,
            prompt,
        })
    );

    if (extractError) {
        console.error("Error processing PDF with LLM provider:", extractError);
        throw extractError;
    }

    const parsed = extractionResult?.data;
    if (!parsed || typeof parsed !== "object") {
        throw new Error("LLM provider did not return structured extraction data");
    }

    // Parse and format the date
    if (parsed.date) {
        try {
            // Parse the date in DD.MM.YYYY format
            const parsedDate = parse(parsed.date, "dd.MM.yyyy", new Date());
            // Format it in ISO format for consistency
            parsed.date = format(parsedDate, "yyyy-MM-dd");
        } catch (dateError) {
            console.error("Error parsing date from the document.");
            throw dateError;
        }
    }

    // Ensure total_amount is a number
    if (parsed.total_amount) {
        parsed.total_amount =
            typeof parsed.total_amount === "string"
                ? parseFloat(parsed.total_amount.replace("€", "").trim())
                : parsed.total_amount;
    }

    // Process itemized expenses
    if (Array.isArray(parsed.itemized_expenses)) {
        parsed.itemized_expenses = parsed.itemized_expenses.map((item) => ({
            ...item,
            amount: typeof item.amount === "string" ? parseFloat(item.amount.replace("€", "").trim()) : item.amount,
            period_start: item.period
                ? parse(item.period.split(" - ")[0], "dd.MM.yyyy", new Date()).toISOString()
                : null,
            period_end: item.period ? parse(item.period.split(" - ")[1], "dd.MM.yyyy", new Date()).toISOString() : null,
        }));
    }

    parsed.description = normalizeDescriptionForExpense(parsed);
    if (!parsed.description || typeof parsed.description !== "string") {
        parsed.description = "SPESA";
    }

    // console.log("parsed", parsed);

    return {
        data: parsed,
        usage: extractionResult?.usage || null,
    };
}

function detectCountryFromAddress(address, vatNumber) {
    // First try from VAT number as it's more reliable
    if (vatNumber) {
        const vatPrefix = vatNumber.substring(0, 2).toUpperCase();
        const vatCountries = {
            DE: "Germania",
            IT: "Italia",
            FR: "Francia",
            GB: "Regno Unito",
            ES: "Spagna",
            NL: "Paesi Bassi",
            BE: "Belgio",
            PT: "Portogallo",
            AT: "Austria",
            CH: "Svizzera",
        };
        if (vatCountries[vatPrefix]) {
            return vatCountries[vatPrefix];
        }
    }

    // If no country from VAT, try from address
    if (address) {
        const addressUpper = address.toUpperCase();
        const countryIndicators = {
            GERMANY: "Germania",
            DEUTSCHLAND: "Germania",
            MÜNCHEN: "Germania",
            MUNCHEN: "Germania",
            FRANCE: "Francia",
            ITALIA: "Italia",
            ITALY: "Italia",
            SPAIN: "Spagna",
            ESPAÑA: "Spagna",
            UK: "Regno Unito",
            "UNITED KINGDOM": "Regno Unito",
            NETHERLANDS: "Paesi Bassi",
            NEDERLAND: "Paesi Bassi",
            BELGIUM: "Belgio",
            BELGIQUE: "Belgio",
            PORTUGAL: "Portogallo",
            AUSTRIA: "Austria",
            SWITZERLAND: "Svizzera",
            SCHWEIZ: "Svizzera",
        };

        for (const [indicator, country] of Object.entries(countryIndicators)) {
            if (addressUpper.includes(indicator)) {
                return country;
            }
        }
    }

    return null;
}

/**
 * Formats the data for creating a received document
 * @param {Object} params - Parameters for formatting the document data
 * @param {Object} params.extractedData - Data extracted from the PDF
 * @param {Object} params.supplier - Supplier information
 * @param {Object} params.paymentAccount - Payment account details
 * @param {Object} params.currency - Currency information
 * @returns {Object} Formatted document data
 */
function formatReceivedDocumentData({ extractedData, supplier, paymentAccount, currency }) {
    const amountGross = extractedData.total_amount;
    const amountVat = extractedData.vat_amount || 0;

    const paidDate = getPaymentDateForExpense(extractedData);

    return {
        type: "expense",
        entity: {
            id: supplier.id,
        },
        date: extractedData.date,
        description: extractedData.description,
        amount_net: amountGross - amountVat,
        amount_vat: amountVat,
        amount_gross: amountGross,
        tax_deductibility: getTaxDeductibilityForExpense(extractedData),
        items_list:
            extractedData.itemized_expenses?.map((item) => ({
                description: item.description || "",
                amount: item.amount,
                period_start_date: item.period_start || null,
                period_end_date: item.period_end || null,
            })) || [],
        payments_list: [
            {
                amount: amountGross,
                due_date: extractedData.date,
                paid_date: paidDate,
                status: "paid",
                payment_terms: {
                    days: 0,
                    type: "standard",
                },
                payment_account: {
                    id: paymentAccount.id,
                },
            },
        ],
        currency,
        language: {
            code: "it",
            name: "Italiano",
        },
    };
}

// Main execution
async function main() {
    const DIR = process.env.DIR || "docs-to-import";
    const doneDirectory = path.join(DIR, "done");
    const runLogPath = path.resolve(RUN_LOG_FILE);
    const rollbackHistoryPath = path.resolve(ROLLBACK_HISTORY_FILE);
    const activeProvider = getActiveProvider();

    const recap = [];
    const llmUsageRows = [];

    p.intro(" pdf-to-fatture-in-cloud");

    const executionType = await p.select({
        message: "Vuoi eseguire le operazioni o solo stampare i dati estratti?",
        options: [
            { value: "run", label: "Esegui" },
            { value: "dry", label: "Solo stampa (dry run)" },
            { value: "rollback", label: "Rollback spese create" },
        ],
    });

    if (p.isCancel(executionType)) {
        p.log.error("Operation cancelled.");
        process.exit(0);
    }

    if (executionType === "rollback") {
        await runRollbackMode({
            historyFilePath: rollbackHistoryPath,
            runLogPath,
            activeProvider,
        });
        return;
    }

    const s = p.spinner();

    s.start("Checking file system structure...");

    // Ensure the 'done' directory exists
    const [mkdirError] = await safe(fs.mkdir(doneDirectory, { recursive: true }));
    if (mkdirError) {
        console.error("Error creating done directory:", mkdirError);
        throw mkdirError;
    }

    // Ensure it can read the files in the directory
    let [readError, files] = await safe(fs.readdir(DIR));

    if (readError) {
        console.error("Error reading directory:", readError);
        throw readError;
    }

    // ignore useless files and directories
    files = files
        // clean hidden files
        .filter((file) => !file.startsWith("."))
        // clean done directory
        .filter((file) => file !== "done");

    s.stop("File system structure checked");

    s.start("Checking files to process...");

    if (files.length === 0) {
        s.stop("Checked files to process");
        p.log.error("No expenses to process found in the directory");
        process.exit(0);
    }

    s.stop(`Files to process: ${files.length}`);
    p.log.info(`LLM provider: ${activeProvider}`);

    s.start("Getting account info from fatture in cloud...");
    const [companiesError, companies] = await safe(listCompanies());

    if (companiesError) {
        console.error("Error fetching companies:", companiesError);
        throw companiesError;
    }

    const company = pickCompany(companies.data.companies);

    if (!company) {
        console.error("No company to use found");
        throw new Error("No company to use found");
    }

    const companyId = company.id;
    s.stop(`Company to register expenses: ${company.name} [id: ${companyId}]`);

    s.start(`Processing files - ${files.length} files`);

    let i = 0;
    for (const file of files) {
        i++;
        p.log.step(`Processing ${file}... ${i}/${files.length}`);
        const isPDF = file.toLowerCase().endsWith(".pdf");
        if (!isPDF) {
            p.log.warn(`Skipping ${file} as it's not a PDF`);
            continue;
        }

        const filePath = path.join(DIR, file);

        const [readFileError, pdfBuffer] = await safe(fs.readFile(filePath));

        if (readFileError) {
            console.error(`Error reading file ${file}:`, readFileError);
            throw readFileError;
        }

        const [extractError, extractionResult] = await safe(processPDFWithLLM(pdfBuffer));
        if (extractError) {
            p.log.error(`Error processing PDF ${file}:`, extractError);
            throw extractError;
        }
        const extractedData = extractionResult.data;

        llmUsageRows.push({
            file: truncateFilename(file),
            provider: extractionResult.usage?.provider || activeProvider,
            model: extractionResult.usage?.model || null,
            input_tokens: extractionResult.usage?.input_tokens ?? null,
            output_tokens: extractionResult.usage?.output_tokens ?? null,
            total_tokens: extractionResult.usage?.total_tokens ?? null,
        });

        if (!extractedData.vendor_name) {
            p.log.error(`Skipping ${file} as it has no vendor name`);
            throw new Error("Skipping file as it has no vendor name");
        }

        // Upload the attachment first

        let attachmentToken = null;
        if (executionType === "run") {
            const [uploadError, token] = await safe(uploadAttachment(companyId, pdfBuffer, file));
            if (uploadError) {
                p.log.error(`Error uploading attachment ${file}:`, uploadError);
                throw uploadError;
            }

            attachmentToken = token;
        }

        // handle the supplier
        let supplier = null;
        let entityStatus = "unknown";
        let entityName = extractedData.vendor_name || "-";
        let entityId = "-";
        let country = extractedData.vendor_country;
        if (!country) {
            country = detectCountryFromAddress(extractedData.vendor_address, extractedData.vat_number);
        }
        const supplierDetails = {
            name: extractedData.vendor_name,
            vat_number: extractedData.vat_number,
            country,
        };

        if (executionType === "run") {
            p.log.step("Checking supplier...");
            const [supplierError, supplierResult] = await safe(getOrCreateSupplier(companyId, supplierDetails));

            if (supplierError) {
                console.log(supplierError.response);
                console.log(JSON.stringify(supplierError.response.data, null, 8));
                throw supplierError;
            }
            supplier = supplierResult.supplier;
            entityName = supplier?.name || entityName;
            entityId = supplier?.id || "-";

            if (supplierResult.new) {
                entityStatus = "created";
                p.log.step(`Supplier created: ${supplier.name}`);
            } else {
                entityStatus = supplierResult.match ? `matched_${supplierResult.match}` : "matched";
                p.log.step(`Supplier found: ${supplier.name} [id: ${supplier.id}]`);
            }

            if (!supplier) {
                p.log.error("No supplier found");
                throw new Error("No supplier found");
            }
        } else {
            p.log.step("Previewing supplier...");
            const [previewError, previewResult] = await safe(previewSupplierResolution(companyId, supplierDetails));
            if (previewError) {
                p.log.error("Error previewing supplier:", previewError);
                throw previewError;
            }

            if (previewResult.supplier) {
                supplier = previewResult.supplier;
                entityStatus = previewResult.match ? `matched_${previewResult.match}` : "matched";
                entityName = previewResult.supplier.name || entityName;
                entityId = previewResult.supplier.id || "-";
                p.log.step(`Supplier matched: ${entityName} [id: ${entityId}]`);
            } else if (previewResult.would_create) {
                entityStatus = "would_create";
                p.log.step(`Supplier not found, would be created: ${entityName}`);
            } else {
                entityStatus = "unresolved";
            }
        }

        // handle the expense
        p.log.step("Creating expense...");
        const currencyCode = extractedData.currency || "EUR";
        const [currencyError, currency] = await safe(findCurrency(currencyCode));
        if (currencyError) {
            p.log.error("Error finding currency:", currencyError);
            throw currencyError;
        }

        const paymentAccountQuery = getPaymentAccountForExpense(extractedData);
        const paymentAccount = await findPaymentAccount(companyId, paymentAccountQuery);

        const expenseData = {
            ...formatReceivedDocumentData({
                extractedData,
                supplier: supplier || { id: "<placeholder>" },
                paymentAccount,
                currency,
            }),
            attachment_token: attachmentToken,
        };

        recap.push({
            file: truncateFilename(file),
            date: expenseData.date,
            description: expenseData.description,
            extraeu: isExtraEuDescription(expenseData.description),
            amount_gross: expenseData.amount_gross,
            tax_deductibility: expenseData.tax_deductibility,
            entity_status: entityStatus,
            entity_name: entityName,
            entity_id: entityId,
            status: executionType === "dry" ? "dry-run" : "pending",
        });
        const recapRow = recap[recap.length - 1];

        if (executionType === "dry") {
            p.log.info(`Expense data: ${JSON.stringify(expenseData, null, 4)}`);
            continue;
        }

        const [expenseError, expense] = await safe(createReceivedDocument(companyId, expenseData));
        if (expenseError) {
            p.log.error("Error creating expense:", expenseError);
            throw expenseError;
        }

        // Move the file to the 'done' directory after successful processing
        const donePath = path.join(doneDirectory, file);
        const [moveError] = await safe(fs.rename(filePath, donePath));
        if (moveError) {
            p.log.error(`Error moving file ${file} to done directory.`);
            throw moveError;
        }
        p.log.success(
            `File ${file} processed, expense created - ${expense.data.date} ${EXPENSE_DETAILS_URL}/${expense.data.id}`
        );
        recapRow.status = "created";
        recapRow.id = expense.data.id;
        recapRow.url = `${EXPENSE_DETAILS_URL}/${expense.data.id}`;

        const rollbackEntry = {
            rollback_entry_id: createRollbackHistoryEntryId(),
            status: "created",
            created_at: new Date().toISOString(),
            company_id: companyId,
            received_document_id: expense.data.id,
            file_name: file,
            source_path: path.resolve(filePath),
            done_path: path.resolve(donePath),
            date: expenseData.date,
            description: expenseData.description,
            amount_gross: expenseData.amount_gross,
            tax_deductibility: expenseData.tax_deductibility,
            entity_status: entityStatus,
            entity_name: entityName,
            entity_id: entityId,
            rollback_events: [],
        };

        const [historyError] = await safe(appendRollbackHistoryEntry(rollbackHistoryPath, rollbackEntry));
        if (historyError) {
            p.log.warn(
                `Expense created but rollback history was not updated (${rollbackHistoryPath}): ${
                    historyError.message || String(historyError)
                }`
            );
        }
    }

    s.stop(`All ${files.length} files processed`);

    console.table(recap);

    const llmRecap = await buildLlmCostRecap(llmUsageRows);
    p.log.info("LLM usage + estimated costs (USD):");
    console.table(llmRecap.rowsWithCosts);
    p.log.info("LLM totals:");
    console.table([llmRecap.totals]);

    if (llmRecap.totalsByProviderModel.length > 1) {
        p.log.info("LLM totals by provider/model:");
        console.table(llmRecap.totalsByProviderModel);
    }

    if (llmRecap.pricingFetchError) {
        p.log.warn(`Unable to fetch model prices from llm-price: ${llmRecap.pricingFetchError}`);
    }
    if (llmRecap.missingModelIds.length > 0) {
        p.log.warn(`Price not found on llm-price for model ids: ${llmRecap.missingModelIds.join(", ")}`);
    }

    const [logError] = await safe(
        appendRunLog({
            executionType,
            activeProvider,
            filesFound: files.length,
            recap,
            llmRecap,
            logFilePath: runLogPath,
        })
    );
    if (logError) {
        p.log.warn(`Unable to append run log at ${runLogPath}: ${logError.message || String(logError)}`);
    } else {
        p.log.info(`Run log updated: ${runLogPath}`);
    }
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
